MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/liyirui/PycharmProjects/ISP-reID/hrnetv2_w32_imagenet_pretrained.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'on'
  DEVICE_ID: ('1')
  NAME: HRNet32
  
  IF_USE_ANGLE: True
  IF_USE_ANGLE_MARGIN: True
  ANGLE_JSON_PATH: "/home/liyirui/PycharmProjects/dataset/BikePerson-700/angle_label.json"
  SAME_ID_DIFF_VIEW: True
  SAME_ID_DIFF_VIEW_WEIGHT: 0.07
  SAME_ID_DIFF_VIEW_MARGIN: 0.01
  DIFF_ID_SAME_VIEW: False
  DIFF_ID_SAME_VIEW_WEIGHT: 0.1
  DIFF_ID_SAME_VIEW_MARGIN: 0.4

  EXTRA:
    FINAL_CONV_KERNEL: 1
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 32
      - 64
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 32
      - 64
      - 128
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 32
      - 64
      - 128
      - 256
      FUSE_METHOD: SUM



INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

CLUSTERING:
  AL: 'Kmeans'
  PERIOD: 2
  STOP: 101
  PART_NUM: 7

DATASETS:
  NAMES: ('bikeperson')
  PSEUDO_LABEL_SUBDIR: ('train_pseudo_labels-ISP-7-26')
  PREDICTED_GT_SUBDIR: ('bounding_box_train_parsing_pgt')
  ROOT_DIR: ('/home/liyirui/PycharmProjects/dataset/')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 120
  BASE_LR: 0.00035

  CLUSTER_MARGIN: 0.3

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005
  
  PARSING_LOSS_WEIGHT: 0.1

  RANGE_K: 2
  RANGE_MARGIN: 0.3
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 32

  STEPS: [40, 70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 20
  EVAL_PERIOD: 10

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: 'no'
  WEIGHT: "/home/liyirui/PycharmProjects/ISP-reID/log/ISP-market-4-120/HRNet32_model_120.pth"
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: "./log/ISP-BikePerson-700-280-train-120-7-angle-26"
